spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: changgou_goods_route
          uri: lb://goods
          predicates:
            - Path=/goods/**,/sku/**,/items/**,/static/**,/css/**,/js/**,/img/**,/img/_/**,/js/plugins/**
          filters:
            - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        #用户微服务
        - id: changgou_user_route
          uri: lb://user
          predicates:
            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
          filters:
            - StripPrefix=1
        #认证微服务
        - id: changgou_oauth_user
          uri: lb://user-auth
          predicates:
            - Path=/oauth/**

        #订单微服务
        - id: changgou_order_route
          uri: lb://order
          predicates:
            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**,/api/wcart/**,/api/worder/**,/api/wxpay/**
          filters:
            - StripPrefix=1


        #秒杀微服务
        - id: changgou_seckill_route
          uri: lb://seckill
          predicates:
            - Path=/api/seckillGoods/**,/api/seckillOrder/**,/api/wseckillgoods/**,/api/wseckillorder/**,/api/seckillwxpay/**
          filters:
            - StripPrefix=1
        #秒杀微服务
        - id: changgou_pay_route
          uri: lb://pay
          predicates:
            - Path=/weixin/pay/notify/**,/weixin/pay/**

  application:
    name: gateway-web
  #Redis配置
  redis:
    host: 192.168.244.132
    port: 6379

server:
  port: 8001



management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      changgou:
        DEBUG