server:
  port: 18081
spring:
  resources:
    static-locations: classpath:/static/
  application:
    name: goods
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.244.132:3306/changgou_goods?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2b8
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false


feign:
  hystrix:
    enabled: true
# 日志配置
#mybatis的配置 可以不配置  需要整合通用mapper
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*Mapper.xml
debug: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      changgou:
        DEBUG


#  type-aliases-package: com.changgou.goods.pojo