server:
  port: 9001
spring:
  application:
    name: user-auth
  redis:
    host: 192.168.244.132
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.244.132:3306/changgou_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2b8
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false


auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou
  clientSecret: changgou
  cookieDomain: 40355s6v21.zicp.vip
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/changgou.jks
    secret: changgou
    alias: changgou
    password: changgou
logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      changgou:
        DEBUG